#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

while IFS=: read -r username password user_id group_id user_info home_directory shell_command; do
    echo "The user ${username} is part of the ${group_id} gang, lives in ${home_directory} and rides ${shell_command}. ${user_id}'s place is protected by the passcode ${password}, more info about the user here: ${user_info}"
done < "/etc/passwd"
