#!/usr/bin/env bash
#Write a Bash script that loops from 1 to 10 and:

#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations

count=0
word=''
while ((count < 10 ))
do
	if ((count == 3)); then
		word='bad luck'
		echo "$word"
		((count++))
	elif ((count == 7)); then
		word='good luck'
		echo "$word"
		((count++))
	else
		word='Best School'
		echo "$word"
		((count++))
	fi
done
