#!/usr/bin/env bash
#Write a Bash script that displays:

#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed (refer to the example)

for file in * # instead of $(ls -1) cause its fragile, not that it doesn't work
do
	echo "$file" | cut -d '-' -f 2-
done
